#!/bin/bash -e
# Script for building OpenH264 for Android PJSIP
# 2020-12-09 Bela Bursan

. config

# # # # # # # # # # # # # # #  OPENH264  # # # # # # # # # # # # # # # # # # #
OPENH264_DOWNLOAD_URL="http://ciscobinary.openh264.org"
# architecture can be: arm or arm64 (or x86, x64)
OPENH264_ARCH=("arm" "arm64")
LIBDIR="$ROOT_LIB_DIR/$OPENH264_DIR_NAME"


## Cleans openh264 stuff
function clean_openh264()
{
    if [ -d "$LIBDIR" ]; then
        rm -rf "$LIBDIR"
    fi
}

# Download openh264
function download_openh264()
{
    echoy "Downloading openh264-$OPENH264_VERSION-$ARCHITECTURE.so.bz2"
    if [ ! -d "$LIBDIR" ]; then
        mkdir -p "$LIBDIR"
    fi

    for arch in "${TARGET_ARCHS[@]}"
    do
        cd "$LIBDIR"
        mkdir -p "$arch/lib"
        cd "$arch/lib"
        curl -L -# -o libopenh264.so.bz2 "$OPENH264_DOWNLOAD_URL/libopenh264-$OPENH264_VERSION-android-$OPENH264_ARCH.so.bz2" 2>&1
        bzip2 -d libopenh264.so.bz2
    done

    echog "OpenH264 downloaded successfully"
    }

# # # # # S T A R T # # #
clean_openh264
download_openh264
