#!/bin/bash -e
# Script for downloading PJSIP
# 2020-12-11 Bela Bursan

. config

# # # # # # # # # # # # # # #  PJSIP  # # # # # # # # # # # # # # # # # # #
PJSIP_DOWNLOAD_URL="https://github.com/pjsip/pjproject/archive"


## Removes old pjsip directories
function clean_dirs()
{
    if [ "$1" == "-f" ]; then
        if [ -d "$WORKING_ROOT_DIR/$PJSIP_DIR_NAME" ]; then
            rm -rf "$WORKING_ROOT_DIR/$PJSIP_DIR_NAME"
        fi
    fi
}


## Download the PJSIP source
function download_pjsip()
{
    echoy "\nDownloading PJSIP v${PJSIP_VERSION} ..."
    if [ -d "$WORKING_ROOT_DIR/$PJSIP_DIR_NAME" ]; then
        echoy "PJSIP already exist"
        return 0
    else
        PJSIP_FILE_NAME="$PJSIP_VERSION.tar.gz"
        cd "$WORKING_ROOT_DIR"

        curl -L -# -o "$PJSIP_FILE_NAME" "$PJSIP_DOWNLOAD_URL/$PJSIP_FILE_NAME" 2>&1

        tar -xzf "$PJSIP_FILE_NAME"
        rm -rf "$PJSIP_FILE_NAME"
        echog "Finished downloading PJSIP"
    fi
}


# # # # # S T A R T # # #
clean_dirs "$1"
download_pjsip
